### PR TITLE
Fix develop tests being skipped

### PR DESCRIPTION
**Pull request by igoumiri**
Fixes https://github.com/LLNL/MuyGPyS/issues/150

### CODE REVIEW

**Comment by igoumiri** [comment]
Tests are failing but kind of randomly.

**Comment by bwpriest** [comment]
This actually explains something odd Alec and I noticed last week, but I didn't realize the problem was in the CI chassis.

> Tests are failing but kind of randomly.

The tests that are failing do so because they are optimizing while we check to see if the output is within some tolerance of the desired answer. There is some randomization, so if we sample a bad batch or something the error can be over the tolerance. We might need to increase the tolerances, since we run these tests so many times.

**Comment by bwpriest** [comment]
I think you can also guard against the multivariate error by changing

https://github.com/LLNL/MuyGPyS/blob/5313d4bebfe057c29430f757e88130b928429b8a/tests/multivariate.py#L367

to 

```
self.assertLessEqual(mse, 0.25)
```

**Review by bwpriest — APPROVED** [review]
LGTM

**Pull request merged**
